; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = dio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.psram_type = qio
board_build.partitions = default_16MB.csv
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
    -Iinclude
    -D USER_SETUP_LOADED=1
    -D ST7796_DRIVER=1
    -D TFT_WIDTH=320
    -D TFT_HEIGHT=480
    -D TFT_MOSI=11
    -D TFT_MISO=13
    -D TFT_SCLK=12
    -D TFT_CS=5
    -D TFT_DC=6
    -D TFT_RST=7
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=1
    -D LOAD_FONT7=1
    -D LOAD_FONT8=1
    -D LOAD_GFXFF=1
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
    -D TOUCH_CS=-1
lib_deps =
    miguelbalboa/MFRC522
    mikalhart/TinyGPSPlus
    adafruit/Adafruit GFX Library
    https://github.com/adafruit/Adafruit_ILI9341.git
    adafruit/DHT sensor library
    https://github.com/Bodmer/TFT_eSPI.git